import type { Metadata } from "next";
import '../sass/global.scss';
import { Fonts } from "@/lib/fonts";

import localFont from '@next/font/local'

import StoreProvider from "@/store/StoreProvider";
import QueryProvider from "@/query/QueryProvider";
import PermissionPopupWrapper from "@/components/PermissionPopup/PermissionPopupWrapper";

import { Toaster } from "sonner";
import GridContainer from "@/components/GridContainer/GridContainer";

const azonix = localFont({
  src: [{
    path : '../assets/fonts/azonix/Azonix.otf',
  }]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <QueryProvider>
            <GridContainer>
                {children}
            </GridContainer>
            <Toaster position="top-right" richColors duration={1200}/>
            {/* <PermissionPopupWrapper /> */}
          </QueryProvider>
        </StoreProvider>

      </body>
    </html>
  );
}